.github/workflows/ci.yml
Fixes #2 
Add the most recent major Python release to our CI builds.
=> ci: add Python 3.8 to linter and test matrix

topo_processor/data/data_transformers/data_transformer_imagery_historic.py
VERY minor bug fix:
changed `return` to `continue` to stop code from exiting for loop
=> fix: prevent script from exiting for loop early

topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py, topo_processor/metadata/metadata_loaders/metadata_loader_tiff.py, topo_processor/stac/collection.py, topo_processor/stac/item.py, topo_processor/util/transfer_collection.py
Update stac metadate to validate against STAC v1.0.0
nb: some workarounds as pypi pystac is outdated
nb: some metadata, i.e.- extents, are not completely implemented (they contain placeholder data)
=> Fix/update stac v1.0.0

topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py
STAC license metadata must comply with https://spdx.org/licenses/
=> fix: use https://spdx.org/licenses/ CC-BY-4.0

.github/CODEOWNERS
To ensure everyone gets automatically tagged in reviews :+1:
=> docs: add Alice as a codeowner

topo_processor/data/data_transformers/data_transformer.py, topo_processor/data/data_transformers/data_transformer_imagery_historic.py, topo_processor/data/data_transformers/data_transformer_repo.py, topo_processor/file_system/tests/get_path_with_protocol_test.py, topo_processor/metadata/metadata_loaders/metadata_loader.py, topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py, topo_processor/metadata/metadata_loaders/metadata_loader_repo.py, topo_processor/metadata/metadata_loaders/metadata_loader_tiff.py, topo_processor/metadata/metadata_validators/metadata_validator.py, topo_processor/metadata/metadata_validators/metadata_validator_imagery_historic.py, topo_processor/metadata/metadata_validators/metadata_validator_repo.py, topo_processor/metadata/metadata_validators/metadata_validator_stac.py, topo_processor/metadata/metadata_validators/metadata_validator_tiff.py, topo_processor/metadata/metadata_validators/tests/metadata_validator_stac_test.py, topo_processor/stac/collection.py, topo_processor/stac/item.py, topo_processor/stac/item_factory.py, topo_processor/util/transfer_collection.py
Changed import statements and used [typing.TYPE_CHECKING](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING) to resolve circular import errors. 
**note:** [(VIDEO) A good explaination of the circular import error and resolution](https://www.youtube.com/watch?v=B5cjckVzY4g&t=315s&ab_channel=anthonywritescode)
=> fix: circular imports

topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py, topo_processor/metadata/metadata_loaders/tests/metadata_loader_imagery_historic_test.py, topo_processor/metadata/metadata_validators/tests/metadata_validator_stac_test.py, topo_processor/stac/collection.py, topo_processor/stac/item.py, topo_processor/stac/item_factory.py, topo_processor/stac/tests/collection_test.py, topo_processor/util/__init__.py, topo_processor/util/conversions.py, topo_processor/util/tests/conversions_test.py, topo_processor/util/tests/transfer_collection_test.py, topo_processor/util/transfer_collection.py
Set the `item.datetime` required property and the `Temporal Extent` for the `Collection`
As the `item.datetime` is a required property for STAC, the item should not be valid/added if this data is missing or invalid in the metadata.
=> feat: set temporal extent (TDE-148)

poetry.lock, pyproject.toml, topo_processor/metadata/metadata_validators/metadata_validator_stac.py
I noted, that you use `json.loads` to load JSON Schema [here](https://github.com/linz/topo-processor/blob/master/topo_processor/metadata/metadata_validators/metadata_validator_stac.py#L24), so I implemented `JSONSchema.from_str` to avoid calling Python's `json` at all in such cases. Locally, it gave substantial speedup for large schemas.
=> chore: Update `jsonschema_rs`

topo_processor/metadata/metadata_validators/metadata_validator_stac.py
urlib gives us `bytes` not a `str`, so it needs to be decoded.
We can maybe always assume it is a `utf-8` encoding these days.
=> fix: bytes need to be decoded first

topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py
Add required extensions and field for the historical-imagery STAC extension
run `validate`
=> fix(metadata-loaders): include required eo and proj metadata in the historical imagery metadata loader

.github/workflows/ci.yml, conftest.py, pyproject.toml, topo_processor/cli/tests/upload_test.py, topo_processor/file_system/tests/write_json_test.py
- Init a `pytest` config file to manage `slow` tests
- Mark integration test in `main_test.py` as `slow` to skip it by default
- Execute `pytest` with `--slow` argument to run the integration test or without to skip it
=> perf: integration test (TDE-191)

topo_processor/cli/tests/upload_test.py, topo_processor/cli/upload.py, topo_processor/data/data_transformers/data_transformer_imagery_historic.py, topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py, topo_processor/stac/asset.py, topo_processor/stac/asset_key.py, topo_processor/util/tests/transfer_collection_test.py, topo_processor/util/transfer_collection.py
[https://linzgovt.atlassian.net/browse/TDE-188](https://linzgovt.atlassian.net/browse/TDE-188)
Note: should I check against the enumerator when adding the key in `topo_processor/util/transfer_collection.py`, rather than assume an enumerator value has been used?
=> fix: asset object key redo (TDE-188)

poetry.lock, pyproject.toml, test_data/schemas/film-schema.json, topo_processor/metadata/metadata_validators/metadata_validator_stac.py, topo_processor/metadata/metadata_validators/tests/metadata_validator_stac_test.py
The JSON schema loader can now load a local schema. 
This is for tests only.
A new test has been added as an example
=> feat(validate): validation against local schema for tests (TDE-234)

README.md, topo_processor/metadata/metadata_validators/tests/metadata_validator_stac_test.py, topo_processor/stac/stac_extensions.py
Release v0.0.11 of our Stac repo changes the schema URLs from linz.github.io/stac to stac.linz.govt.nz.
This is to update the Topo Processor with the new URLs.
=> feat: update extension urls to stac.linz.govt.nz

.github/workflows/ci.yml, pyproject.toml
Mypy configuration is not checking all the current errors by default. That means `mypy .` run on the current code base will not raise any error.
Mypy run is added to the CI workflow. `mypy .` will be run at every build on the GitHub repository.
Run `mypy .` at the project root. Make sure that it returns `Success: no issues found in [...]`
=> ci: add mypy run to the CI workflow (TDE-184)

pyproject.toml, topo_processor/cli/validate.py, topo_processor/file_system/write_json.py, topo_processor/metadata/metadata_loaders/tests/metadata_loader_imagery_historic_test.py, topo_processor/stac/asset.py, topo_processor/stac/collection.py, topo_processor/stac/tests/lds_cache_test.py, topo_processor/stac/validation.py, topo_processor/util/__init__.py, topo_processor/util/aws_credentials.py, topo_processor/util/aws_files.py, topo_processor/util/configuration.py, topo_processor/util/time.py
Add the missing typing for function arguments. That is check by `Mypy` with error code `arg-type`
run `mypy .` should not display any error.
=> fix: add missing typing for function arguments [arg-type] (TDE-263)

pyproject.toml, topo_processor/cog/command.py, topo_processor/data/data_transformers/data_transformer.py, topo_processor/metadata/metadata_loaders/metadata_loader.py, topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py, topo_processor/metadata/metadata_validators/metadata_validator.py, topo_processor/stac/asset.py, topo_processor/stac/collection.py, topo_processor/stac/item.py, topo_processor/stac/linz_provider.py, topo_processor/util/aws_files.py, topo_processor/util/configuration.py, topo_processor/util/gzip.py, topo_processor/util/valid.py
Fixes: [TDE-277](https://linzgovt.atlassian.net/browse/TDE-277)
fix all mypy assignment errors
nb: ignored one due to conflict with STAC providers, this is related to https://github.com/radiantearth/stac-spec/issues/1147
`mypy .` should pass without error
=> fix: mypy assignment (TDE-277)

conftest.py, pyproject.toml, topo_processor/cli/tests/upload_test.py, topo_processor/file_system/tests/transfer_test.py, topo_processor/file_system/tests/write_json_test.py, topo_processor/util/tests/aws_files_test.py, topo_processor/util/tests/files_test.py, topo_processor/util/tests/time_test.py, topo_processor/util/tests/transfer_collection_test.py
Use `Generator` type for return type annotation of `pytest` `setup()` functions.
=> fix: typing annotation None to Generator for pytest setup functions (TDE-285)

pyproject.toml
The exclusion list for the mypy error code has only the `import` error code that we don't want to show.
run `mypy .`
=> config: remove unused mypy error code from the exclusion list (TDE-287)

Dockerfile, topo_processor/cog/create_cog.py
This is part of [https://toitutewhenua.atlassian.net/browse/TDE-220](https://toitutewhenua.atlassian.net/browse/TDE-220)
To run the topo-processor inside Docker on your local workstation:
From the directory where the Dockerfile is:
`docker build -t topo-processor-image .`
`docker run --name topo-processor -dt topo-processor-image:latest`
`docker exec -it topo-processor /bin/bash`
`./upload --source test_data --target build/test_output --datatype imagery.historic --verbose`
(so you can explore the filesystem and see the output without mapping any drives).
This Docker image is a starting point to be used with the AWS Batch infrastructure, as in the topo-aws-infrastrure gdalinfo code. It will probably need some AWS account helper stuff to be added.
Further changes will be needed to the …
=> feat: create Dockerfile

topo_processor/stac/lds_cache.py, topo_processor/stac/tests/lds_cache_test.py
Not all assets should be decompressed automatically, only decompress the ones that have a `ContentEncoding` set
this also changes the behaviour to look for the last "rel: item" in the collection links  rather than just the last record in the list as not everything in that list is a "rel: item"
=> feat: use stac encoding field 

topo_processor/metadata/metadata_loaders/metadata_loader_tiff.py, topo_processor/metadata/metadata_validators/metadata_validator_tiff.py
Currently rasterio provides the warning message:
```/usr/local/lib/python3.8/dist-packages/rasterio/io.py:131: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.```
This is ok as we are not expecting historical imagery to be georeferenced but have decided to 'catch' the warning to log them in a similar fashion to other topo-processor logs and to associate the warning with the tiff file it relates to.
=> feat: catch rasterio warnings to log

topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py, topo_processor/util/gzip.py
When using the lds cache metadata the code was completing but with null geometries:
```json
{
"error": [
{
"msg": "Geometry is missing",
"level": "warning",
"cause": "",
"error": null
}
],
"level": 40,
"time": 1643744247646,
"v": 1,
"pid": 1,
"msg": "Item 36925 contains warnings:"
}
```
This was due to the WKT csv name being `\\ufeffWKT`
=> fix: allow for unicode character in metadata csv

infra/src/submit.ts
Questions:
- Would it be better to do this on the Python side?
- Should we be using the correlationId instead of a new ulid for the temp directory?
=> feat: add correlationId to target location TDE-173

topo_processor/file_system/file_searcher.py, topo_processor/metadata/lds_cache/lds_cache.py
- A logging has been removed as it is not really useful to know if a key exists or not.
- The metadata filtered by survey id is now saved (when `upload` is called with a survey id - not a path) which improve performances as the next search for items in the metadata is done on the filtered records and not the full list of records.
=> fix: change logs for filter_metadata and avoid looping over all metadata records while upload with survey ID (TDE-326)

topo_processor/metadata/metadata_validators/metadata_validator_tiff.py, topo_processor/metadata/metadata_validators/tests/metadata_validator_tiff_test.py
Rasterio was used to get the band information from the TIFF and also to get it again for checking the metadata.
This PR is to remove Rasterio from the second check, using the values originally got from the TIFF.
=> perf: do not use rasterio to check tiff band validity TDE-333

.github/workflows/build.ts.yml, infra/src/batch-monitor.ts, infra/src/index.ts, infra/src/lambda-code/index.js
Creates a lambda function to log to elastic search events in `li-topo-prod` and `li-topo-nonprod` that follow the pattern:
```
source: ['aws.batch'],
detailType: ['Batch Job State Change'],
detail: { status: ['FAILED'] },
```
**nb: I added `--all` to the nonprod and prod deployment workflows in `.github/workflows/build.ts.yml` this means it should deploy both `TopoProcessorBatch` and `TopoProcessorMon` on merge to master for nonprod and on publish for prod.** - Is this ok?
=> feat(cdk): lambda function to monitor batch job failures

CHANGELOG.md, package.json
Testing to see if the error was a transient error, as it passed the test when the previous PR was merged.
=> release: 0.6.0

infra/src/batch.ts
This PR goes with [https://github.com/linz/topo-aws-infrastructure/pull/44](https://github.com/linz/topo-aws-infrastructure/pull/44) to manage the users in the topo-aws-infrastructure code instead of in the Topo Processor code.
=> fix: provision user in aws infrastructure repo

scripts/version.bump.sh
When a new release is made, the git tag, package.json, pyproject.toml and VERSION files are updated with the new version number.
The pyproject.toml and VERSION files are never committed so do not get updated with the release.
This fix is to commit all the changes.
=> fix: TDE-383 commit VERSION and pyproject.toml files

README.md, topo_processor/cli/geostore/add.py, topo_processor/cli/geostore/list.py, topo_processor/cli/geostore/status.py
This also reverses the previous change to listing by `survey` and `datatype` as it was better in some ways but worse in others (couldn't list all datasets).
=> fix: TDE-404 geostore CLI logging changes and revert list data type search
