.github/workflows/ci.yml
Everything currently supports python 3.8
Join test/lint job together
=> ci: reduce complexity of build pipeline

topo_processor/metadata/collection_factory.py, topo_processor/metadata/loaders/metadata_loader_repo.py
=> feat: added more logger to log important messages

topo_processor/metadata/loaders/metadata_loader_imagery_historic.py, topo_processor/metadata/loaders/metadata_loader_imagery_historic_test.py
=> fix: speed up csv extractor

topo_processor/cli/main.py, topo_processor/cli/tests/main_test.py, topo_processor/cog/command.py, topo_processor/cog/create_cog.py, topo_processor/cog/tests/command_test.py, topo_processor/cog/tests/create_cog_test.py, topo_processor/imagery/transformers/data_transformer_imagery_historic.py, topo_processor/metadata/loaders/tests/metadata_loader_imagery_historic_test.py, topo_processor/metadata/loaders/tests/metadata_loader_tiff_test.py, topo_processor/metadata/validators/tests/metadata_validator_tiff_test.py, topo_processor/stac/collection.py, topo_processor/stac/collection_factory.py, topo_processor/stac/item.py, topo_processor/uploader/local.py, topo_processor/uploader/s3.py
transformed tiffs and json files are stored in the same tmp folder.
note: json files are only stored here for the s3 upload, they are stored in the target folder for the local upload
=> transformed tiffs and json files are stored in the same tmp folder

.github/workflows/ci.yml, .gitignore, poetry.lock, pyproject.toml
run through `pytest --cov topo_processor`
=> test: add coverage check

poetry.lock, pyproject.toml, topo_processor/cli/tests/main_test.py, topo_processor/cog/tests/command_test.py
=> tests: stub/mock docker test

poetry.lock, pyproject.toml, topo_processor/data/data_transformers/data_transformer_imagery_historic.py, topo_processor/stac/collection.py
Fixes: #  
_Add new line for each issue that was fixed_
...
...
=> build: switch to python-ulid to be consistent across LINZ

topo_processor/cog/command.py, topo_processor/cog/create_cog.py, topo_processor/cog/execution.py, topo_processor/data/data_transformers/data_transformer_imagery_historic.py, topo_processor/file_system/get_fs.py, topo_processor/file_system/tests/get_fs_test.py, topo_processor/stac/item_factory.py, topo_processor/util/aws_credentials.py
uses vsis3 and adds aws credentials as env variables to docker command to take s3 input files for cogging.
=> feat: cog from s3

poetry.lock, topo_processor/cli/main.py, topo_processor/cli/validate.py, topo_processor/data/data_transformers/data_transformer_imagery_historic.py, topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py, topo_processor/metadata/metadata_loaders/metadata_loader_repo.py, topo_processor/metadata/metadata_loaders/metadata_loader_tiff.py, topo_processor/metadata/metadata_validators/metadata_validator.py, topo_processor/metadata/metadata_validators/metadata_validator_imagery_historic.py, topo_processor/metadata/metadata_validators/metadata_validator_repo.py, topo_processor/metadata/metadata_validators/metadata_validator_tiff.py, topo_processor/stac/item_factory.py
Cleanup following https://lgtm.com/projects/g/linz/topo-processor/?mode=list
=> fix: cleanup as per Semmle/lgtm report (TDE-181)

.github/workflows/ci.yml
Pull requests from external acocunts were not being run through CI.
=> ci: build on pull request and pushes

.env, README.md, poetry.lock, pyproject.toml, topo_processor/cog/create_cog.py, topo_processor/util/aws_credentials.py, topo_processor/util/configuration.py, topo_processor/util/tests/aws_credentials_test.py
Link AWS roles local configuration file to be used by `topo-processor`
N/A
=> config(AWS): initialize configuration for AWS roles (TDE-176)

topo_processor/metadata/metadata_loaders/metadata_loader_imagery_historic.py, topo_processor/metadata/metadata_loaders/metadata_loader_tiff.py, topo_processor/metadata/metadata_loaders/tests/metadata_loader_imagery_historic_test.py, topo_processor/metadata/metadata_loaders/tests/metadata_loader_tiff_test.py, topo_processor/metadata/metadata_validators/metadata_validator_stac.py, topo_processor/metadata/metadata_validators/tests/metadata_validator_stac_test.py, topo_processor/stac/collection.py, topo_processor/stac/item.py, topo_processor/stac/stac_extensions.py, topo_processor/util/tests/transfer_collection_test.py, topo_processor/util/transfer_collection.py
Utilises pystac.Summarizer.summarize() and a custome fields.json url to construct the summaries for Historical Imagery.
=> feat: implement summaries

pyproject.toml, topo_processor/stac/lds_cache.py
correct issue with union attribute typing `[union-attr]`
=> fix: correct issue with union attribute typing [union-attr] (TDE-268)

pyproject.toml, topo_processor/data/data_transformers/data_transformer_repo.py, topo_processor/stac/asset.py
**Change Description:**
Correct return value errors, mypy error code `return-value`
[https://linzgovt.atlassian.net/browse/TDE-265](https://linzgovt.atlassian.net/browse/TDE-265)
**Notes for Testing:**
run `mypy` . should not display any error.
=> fix: mypy [return-value] (TDE-265)

pyproject.toml, topo_processor/stac/asset.py, topo_processor/stac/collection.py, topo_processor/stac/item.py, topo_processor/util/aws_credentials.py, topo_processor/util/conversions.py
Add the missing typing for type arguments. That is check by Mypy with error code type-arg
run `mypy .` should not display any error.
=> fix: add missing typing for type arguments [type-arg] (TDE-266)

.env, pyproject.toml, topo_processor/util/configuration.py
fix `mypy` complains about variable values type `[type-var]`
=> fix: variable values type [type-var] (TDE-281)

pyproject.toml, topo_processor/metadata/metadata_loaders/metadata_loader.py, topo_processor/metadata/metadata_loaders/metadata_loader_tiff.py
Fix abstract method signature to comply with [override] (TDE-180)
=> fix: abstract method signature to comply with [override] (TDE-180)

pyproject.toml, topo_processor/stac/collection.py, topo_processor/stac/tests/collection_test.py
Mypy makes sure that the item is compatible with the list type with `[list-item]`
=> fix: item compatible with the list type [list-item] (TDE-282)

.eslintrc.cjs, .github/workflows/ci.yml, .prettierrc.cjs, infra/src/batch.ts, infra/src/index.ts, infra/src/submit.ts, package.json, tsconfig.json, yarn.lock
Fixes: #  
_Add new line for each issue that was fixed_
...
...
=> ci: add javascript lint and format

infra/src/batch.ts, infra/src/index.ts, infra/src/submit.ts
Like a phoenix from the ashes of my previous two pull requests...
This is to give the stack some more descriptive names, create an S3 bucket, and assign permissions.
=> feat: config for aws stacks TDE-173

README.md
=> fix: update readme TDE-173

topo_processor/file_system/transfer.py, topo_processor/stac/collection.py, topo_processor/stac/item.py
- Checksum on file transferred
- collection.id on stac collection object created
- item.id on stac item object created
=> feat: log unique values
